# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-05 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='palte',
            new_name='plate',
        ),
    ]
