# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 20:39
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth import get_user_model


def setup_first_user(apps, schema_editor):
    User = get_user_model()
    user = User.objects.create_user("geovani.lopes","geovani.lopes@gmail.com","dedhio")


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_first_user)
    ]
